FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

RUN apt-get update && apt-get --assume-yes install wget build-essential libclang-dev protobuf-compiler

RUN wget "https://github.com/microsoft/onnxruntime/releases/download/v1.20.0/onnxruntime-linux-x64-1.20.0.tgz" && \
    tar -xzf onnxruntime-linux-x64-1.20.0.tgz && \
    rm onnxruntime-linux-x64-1.20.0.tgz && \
    mv onnxruntime-linux-x64-1.20.0 onnxruntime && \
    mv onnxruntime/include/* /usr/include/ && \
    mv onnxruntime/lib/libonnxruntime* /usr/lib/x86_64-linux-gnu

ENV ORT_LIB_LOCATION=/usr/lib/x86_64-linux-gnu
