FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge

RUN apt-get update && apt-get --assume-yes install wget build-essential libclang-dev protobuf-compiler

RUN wget "https://github.com/microsoft/onnxruntime/releases/download/v1.20.0/onnxruntime-linux-aarch64-1.20.0.tgz" && \
    tar -xzf onnxruntime-linux-aarch64-1.20.0.tgz && \
    rm onnxruntime-linux-aarch64-1.20.0.tgz && \
    mv onnxruntime-linux-aarch64-1.20.0 onnxruntime && \
    mv onnxruntime/include/* /usr/include/ && \
    mv onnxruntime/lib/* /usr/lib/aarch64-linux-gnu/
