name: build linux

on:
  workflow_dispatch:

jobs:
  build:
    name: build linux

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Check number of CPU cores
        run: |
          echo Cores - ${{ steps.cpu-cores.outputs.count }}

      - name: Install wild
        run: |
          wget "https://github.com/davidlattimore/wild/releases/download/0.5.0/wild-linker-x86_64-unknown-linux-gnu.tar.xz"
          tar xf wild-linker-x86_64-unknown-linux-gnu.tar.xz
          mv wild-linker-x86_64-unknown-linux-gnu/wild /usr/local/bin/wild
          chmod +x /usr/local/bin/wild
          /usr/local/bin/wild --version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"

      - name: Build
        run: cargo build
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
          RUSTFLAGS: -Zthreads=${{ steps.cpu-cores.outputs.count }} -Clink-arg=--ld-path=/usr/local/bin/wild

      - name: Check binary
        run: readelf -p .comment target/debug/extract-speech
