name: build macos

on:
  workflow_dispatch:

jobs:
  build:
    name: build macos

    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        run: brew install protobuf

      - name: Build
        run: cargo build --features "accelerate-src"
  
