name: build windows

on:
  push:

jobs:
  build:
    name: build windows

    runs-on: windows-latest

    env:
      LIBOPUS_STATIC: "1"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use cmake
        run: cmake --version
    
      - name: Use clang
        run: clang --version
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 'latest'
      
      - name: Use cmake
        run: cmake --version

      - name: Build
        run: cargo build
