name: release linux x86_64

on:
  workflow_dispatch:

jobs:
  build:
    name: release linux x86_64

    runs-on: depot-ubuntu-24.04-16

    env:
      LIBOPUS_STATIC: "1"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 'latest'

      - name: Use cmake
        run: cmake --version

      - name: Install LLD
        run: sudo apt install -y lld

      - name: Use LLD
        run: ld.lld --version

      - name: Build
        run: cargo build --release
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
          RUSTFLAGS: -Clink-arg=-fuse-ld=lld -Ctarget-cpu=native

      - name: Check binary
        run: readelf -p .comment target/release/extract-speech

      - name: Upload release artifact
        uses: actions/upload-artifact@v5
        with:
          name: extract-speech_x86_64_linux
          path: target/release/extract-speech
