name: release macos aarch64

on:
  workflow_dispatch:

jobs:
  build:
    name: release macos aarch64

    runs-on: macos-latest

    env:
      LIBOPUS_STATIC: "1"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 'latest'

      - name: Use cmake
        run: cmake --version

      - name: Build
        run: cargo build --target aarch64-apple-darwin --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: extract-speech_aarch64_apple_darwin
          path: target/aarch64-apple-darwin/release/extract-speech
